import { CONFIGS } from '../../config';

export function generatePostSeed(title: string): string {
  return `# ${CONFIGS.POST_NAME_PREFIX} ${title}\n## 5 Ways to evaluate content
So, what are you testing for? There are five main ways to evaluate content, each looking at a different key aspect for in-product content success:
- **Usability**: Usability refers to testing how easy your product’s content is to engage with. Product content doesn’t afford the same character flexibility as other content, so brevity is everything. However, brevity gives you fewer words to communicate with—ensuring users understand your product content is key.
- **Readability**: You want your content to be readable by your users from the get-go, not after numerous readthroughs. Remember that your users will expect to be able to scan the text rather than reading every word.
- **Accessibility**: Accessibility refers to your product’s ability to provide a great experience to all users. Consider how screen-readers or other accessibility aids will interact with your content. Not only does this widen your audience, but it [creates an inclusive product](https://maze.co/guides/inclusive-design/) that everyone can use.
- **Searchability**: This is to do with search engine optimization (SEO) and dictates whether people are able to find your website or product easily online. Getting it right can hugely increase the numbers of people who find and read your content.
- **Tone and voice**: Finally, you should consider the tone and voice of your content. Your product, like your brand, has a voice it uses to speak to users, so making sure each piece of content resonates with your audience is important.

Looking out for these five areas when testing your content will help ensure it’s exactly what your audience wants.`;
}

export function generateArticleSeed(title: string): { title: string; content: string } {
  return {
    title: `${CONFIGS.ARTICLE_NAME_PREFIX} ${title}`,
    content:
      '[{"type":"h2","children":[{"text":"When should you perform content testing?"}],"id":"hMAp9HHxWsTmV-s009m_F"},{"type":"p","align":"left","children":[{"text":"Determining the right stage of development to test your content is tricky. On the one hand, you want your content to reflect the real content your users will encounter. On the other, you don’t want to spend lots of time creating fully-formed and finalized content only to discover it’s not what your users need."}],"id":"teNYRADgmn9rfQ-RoQNI-"},{"type":"p","align":"left","children":[{"text":"Ultimately, like most types of research and user testing, content testing works best when used iteratively at multiple stages in the design process. You can use content testing:"}],"id":"8frlAi1e6uUKlyasvbOov"},{"type":"ul","children":[{"children":[{"indent":0,"listStyleType":"","type":"lic","children":[{"text":"During the conceptualization phase, you can use content testing to understand the broad framework of content you’ll need (what information they need, the language they use etc.) and get an overview of the conversation you’ll be having."}],"id":"OmfU5YhcrBtCNNS7ZFfMN"}],"type":"li","id":"jRz-1iHMCZ_FqzoSgx4ve"},{"children":[{"indent":0,"listStyleType":"","type":"lic","children":[{"text":"Midway through design, you can run content tests to validate your current content and understand where you may want to change direction, before you invest too much time in the wrong area. Content testing at this stage can be invaluable in understanding whether you’re meeting your goals; are you confusing or communicating?"}],"id":"Xw2cHHzmU8e3SQuNjeIoK"}],"type":"li","id":"Z5QZoHlM8_HxLMTcAdSV8"},{"children":[{"indent":0,"listStyleType":"","type":"lic","children":[{"text":"Close to and after launch, content testing is invaluable to check that the content—after your iterations—is clear to all potential users and achieves what you set out to do. How does it make users feel after they read it? Does it work with accompanying design or imagery? Here, you can also make any last minute changes."}],"id":"iLQMCCji8z8AsbGL85gpo"}],"type":"li","id":"kCF64JOFesIAjsgYDydCT"}],"id":"5EsQFI-r1qM4CBR5zTSSx"},{"children":[{"text":""}],"type":"p","id":"B-xEpnDAZwojMISyoIGEI"}]',
  };
}
